"""added_subscription_date

Revision ID: 377d16de4439
Revises: 762c100522cd
Create Date: 2023-02-26 16:51:41.361329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377d16de4439'
down_revision = '762c100522cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_date', sa.DateTime(), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_date')
    # ### end Alembic commands ###
