"""added_chat_id

Revision ID: 762c100522cd
Revises: eb07de74ac02
Create Date: 2023-02-26 16:39:10.223035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762c100522cd'
down_revision = 'eb07de74ac02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.VARCHAR(50), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###
